### ISSUE TITLE
AttributeError: module 'telegram_send' has no attribute 'send'

### ISSUE THREAD

**Issue by MelanX** [rahiel/telegram-send#47] opened 2019-01-11 20:15 UTC
I installed and configured telegram-send. I tried in bash and it works. But Python doesn't work.
Here is a video where I tried the script from the documentation: https://youtu.be/iCgjwXae1co
Here is the full error: https://pastebin.com/cMuCTmp5

OS: Raspbian stretch from 2018-11-13
Python: 3.7.2

If you need more information tell me please.

**Comment by rahiel** [comment] 2019-01-15 09:10
How did you install `telegram-send`?

**Comment by MelanX** [comment] 2019-01-16 05:57
sudo pip3 install telegram-send

**Comment by aydindemircioglu** [comment] 2019-05-30 00:55
same here

**Comment by aydindemircioglu** [comment] 2019-05-30 01:03
the import in python3 must be broken somehow--

import telegram_send
print ("i am getting started")

gives "i am getting started" TWICE as output.  after looking around i see this, but no solution?

https://github.com/python-telegram-bot/python-telegram-bot/issues/1225

**Comment by aydindemircioglu** [comment] 2019-05-30 01:04
a fix would be to make sure that the file is not executed when loaded as non-main, so this works:

if __name__ == "__main__":
    telegram_send.send(messages=["S"])

though the file is loaded still twice.

**Comment by rahiel** [comment] 2019-10-13 10:21
@MelanX, I think the problem is from calling calling your script `test.py.`.

1) Please upgrade telegram send: `sudo pip3 install telegram-send --upgrade`
2) Give your script a name that is not `test.py`, for example `main.py`

**Comment by rahiel** [comment] 2022-04-09 23:06
This should be fixed in the latest version and with the suggestions above.

**Closed by rahiel** 2022-04-09 23:06 UTC
Labels: question
